# Generated by Django 5.2 on 2026-08-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('currentPosition', models.CharField(blank=True, default='', max_length=300)),
                ('organization', models.CharField(blank=True, default='', max_length=300)),
                ('photo', models.CharField(blank=True, default='', max_length=2000)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConvenerInfo',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=300)),
                ('quote', models.TextField(blank=True, default='')),
                ('welcomeMessage', models.TextField(blank=True, default='')),
                ('photo', models.CharField(blank=True, default='', max_length=2000)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('coverImage', models.CharField(blank=True, default='', max_length=2000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('videoUrl', models.CharField(blank=True, default='', max_length=2000)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(default='Landscape', max_length=100)),
                ('image', models.CharField(blank=True, default='', max_length=2000)),
                ('photographer', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('facebook', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin', models.CharField(blank=True, default='', max_length=500)),
                ('instagram', models.CharField(blank=True, default='', max_length=500)),
                ('photo', models.CharField(blank=True, default='', max_length=2000)),
                ('order', models.IntegerField(default=1)),
                ('quote', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Celebration', 'Celebration'), ('Announcement', 'Announcement'), ('Achievement', 'Achievement')], default='Announcement', max_length=40)),
                ('image', models.CharField(blank=True, default='', max_length=2000)),
                ('content', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=2000)),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('published', 'published'), ('upcoming', 'upcoming')], default='published', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('contactEmail', models.CharField(blank=True, default='', max_length=254)),
                ('contactPhone', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=600)),
                ('facebookUrl', models.CharField(blank=True, default='', max_length=2000)),
                ('instagramUrl', models.CharField(blank=True, default='', max_length=2000)),
                ('youtubeUrl', models.CharField(blank=True, default='', max_length=2000)),
                ('linkedinUrl', models.CharField(blank=True, default='', max_length=2000)),
                ('heroTitle', models.CharField(blank=True, default='', max_length=300)),
                ('heroSubtitle', models.CharField(blank=True, default='', max_length=300)),
                ('motto', models.TextField(blank=True, default='')),
                ('mottoBgImages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
